package marathon

import (
	"log"
	"encoding/json"
	"strconv"
	"../common/api"
)


type MSDeployer interface {
	GetApps() AutoGenerated
	CreateApp(app MarathonApp)
	SetAppInstances(app MarathonApp, instances int)
	DeleteApp(appID string)
}

var cli = api.HttpClient{"http://localhost:8080/v2"}

func GetApps() AutoGenerated {
	var body = cli.GetCall("/apps")

	var apps AutoGenerated

	err  := json.Unmarshal(body, &apps)

	if err != nil {
		log.Fatal(err)
	}

	return apps
}

func CreateApp(app MarathonApp) {
	b, err := json.Marshal(app)
	if err != nil {
		log.Fatal(err)
	}
	cli.PostCall("/apps", string(b))
}

func SetAppInstances(app MarathonApp, instances int) {
	app.Instances = instances

	cli.PutCall("/apps/"+app.ID, "{\"instances\": "+strconv.Itoa(instances)+"}")
}

func DeleteApp(appID string) {
	cli.DeleteCall("/apps/"+appID)
}
